name: msf
channels:
  - conda-forge
  - defaults
dependencies:
  - tbb-devel=2021.10
  - eigen=3.4.0
  - fmt=10.2.1
  - cgal=5.6
  - cli11=2.3.2
  - nanoflann=1.5.1
  - mkl=2023.1.0
  - mkl-devel=2023.1.0
  - openvdb=10.0.1
